apiVersion: v1
kind: Service
metadata:
  name: openflights-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: openflights-app
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }}