apiVersion: v1
kind: Service
metadata:
  name: openflights-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: openflights-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None