apiVersion: apps/v1
kind: Deployment
metadata:
  name: openflights-redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openflights-redis
  template:
    metadata:
      labels:
        app: openflights-redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: 6379