apiVersion: apps/v1
kind: Deployment
metadata:
  name: openflights-sidekiq
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.sidekiq.replicas }}
  selector:
    matchLabels:
      app: openflights-sidekiq
  template:
    metadata:
      labels:
        app: openflights-sidekiq
    spec:
      containers:
      - name: sidekiq
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bundle", "exec", "sidekiq"]
        envFrom:
        - configMapRef:
            name: openflights-config