apiVersion: v1
kind: Secret
metadata:
  name: openflights-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/oluty/openflights-gitops.git
  username: oluty
  password: <your-github-personal-access-token>